Add friends likes
SergKostarev/java-filmorate pull request #3
Opened 2024-08-27 19:29 UTC by SergKostarev

2024-08-28 19:15 UTC, z8q requested changes

2024-08-28 19:15 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Можно привести последовательность выполнения команд к одной схеме 
controller -> service ->  storage
разделить зоны ответственности так, что
- контроллер валидирует и принимает запросы / возвращает ответы
- сервис выполняет определенную логику по запросу
- storage отвечает за сохранение данных

Тут тогда останется только поле UserService userService и все запросы будут идти через сервис

2024-08-28 19:15 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = userStorage.findUser(id);
можно сделать проверку на равенство id и friendId, чтобы ограничить возможность добавления самого себя в друзья

2024-08-28 19:15 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (count < 1) {
Можно поставить аннотацию `@Positive`, тогда строки 64-70 можно будет убрать
```
getMostPopular(@Positive @RequestParam(defaultValue = "10") Integer count)
```
Если будем использовать валидационные аннотации на аргументах методов, еще нужно будет над классом контроллера поставить `@Validated` для корректной работы

2024-08-28 19:15 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleRuntime(RuntimeException e) {
При использовании слишком общих исключений, типа RuntimeException или Throwable, 
могут возникать такие случаи, когда ошибка возникает с каким-то определенным сообщением,  но мы заменяем его на "Произошла непредвиденная ошибка."

Или можем еще коды ответа 4** например этим хендлером заменять на 5**

В общем надо использовать с осторожностью)

2024-08-29 18:30 UTC, SergKostarev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (count < 1) {
Исправил

2024-08-29 18:31 UTC, SergKostarev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = userStorage.findUser(id);
Эта проверка есть в UserController, строка 84

2024-08-29 18:42 UTC, SergKostarev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Исправил

2024-08-29 18:45 UTC, SergKostarev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleRuntime(RuntimeException e) {
Учту)
Мне тоже это показалось не совсем правильным, но в задании так.

2024-08-30 18:15 UTC, z8q approved these changes

2024-09-07 13:02 UTC, merged