Add database
SergKostarev/java-filmorate pull request #4
Opened 2024-09-26 18:57 UTC by SergKostarev

2024-09-27 19:28 UTC, z8q requested changes

2024-09-27 19:28 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>                  .toList();
можно посмотреть, как отработает var commonFriends = friends.retainAll(otherFriends);
вместо дополнительного обращения к базе

2024-09-27 19:28 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            jdbc.update(ADD_FILM_GENRE_QUERY, id, g.getId());
стоит избегать обращений к базе в циклах и стримах
если есть возможность передавать значения списком в запросе, то стоит выполнять одним запросом

2024-09-27 19:28 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            jdbc.update(ADD_FILM_GENRE_QUERY, id, g.getId());
в 111 строке тоже можно посмотреть

2024-09-27 19:28 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            return Optional.of(jdbc.queryForObject(GET_FILM_RATING, ratingMapper, filmId));
если может приходить null то стоит использовать Optional.ofNullable

2024-09-28 14:12 UTC, SergKostarev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                .toList();
Исправил

2024-09-28 14:14 UTC, SergKostarev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                .toList();
Исправил

2024-09-28 14:21 UTC, SergKostarev commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@Validated
Исправил

2024-09-28 14:22 UTC, SergKostarev commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +                .toList();
Исправил

2024-09-28 14:27 UTC, SergKostarev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Rating mpa = null;
Исправил

2024-09-28 14:28 UTC, SergKostarev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void isValid(Film film) {
Исправил

2024-09-28 14:48 UTC, SergKostarev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        for (Genre genre : film.getGenres()) {
Исправил

2024-09-28 15:48 UTC, SergKostarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            jdbc.update(ADD_FILM_GENRE_QUERY, id, g.getId());
Исправил. Добавил метод void addFilmGenres(Film film), где используется jdbc.batchUpdate()

2024-09-28 16:02 UTC, SergKostarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            return Optional.of(jdbc.queryForObject(GET_FILM_RATING, ratingMapper, filmId));
Исправил

2024-09-28 16:29 UTC, SergKostarev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>                  .toList();
Исправил

2024-09-29 18:36 UTC, z8q approved these changes

2024-10-03 06:32 UTC, merged